name: PR Comic Strip
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  comic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build action
        run: npm run build
      
      - uses: ./
        id: comic
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      
      - name: Upload comic as artifact
        if: always()
        uses: actions/upload-artifact@v4
        id: upload
        with:
          name: pr-comic-strip
          path: comic-art/comic-1x4.png
          if-no-files-found: ignore
      
      - name: Comment with comic link
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const runId = context.runId;
            const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${runId}/artifacts`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🎨 **Comic Strip Generated!**\n\n![PR Comic Strip](${artifactUrl})\n\n[📥 Download Comic Strip](${artifactUrl})\n\n*Generated from the commits in this PR*`
            })